### PR TITLE
Ensure correct payment mode is added to monthly subscriptions

### PR DESCRIPTION
**Pull request by stevenmc**

### CODE REVIEW

**Review by naokipeter — COMMENTED** [review]
Permitted values for mode are "live" and "sandbox". Whether or not a donation is one-time or recurring is stored in frequency.

**Comment by stevenmc** [comment]
Without this code change, when I try to make a recurring payment using Stripe, I get the error:
"You can not pass `subscription_data` in `payment` mode."
Please check this before closing the PR. Thanks.

**Comment by stevenmc** [comment]
By the way, your comment is incorrect as you're mixing up the variable $mode with the sessionParam['mode'];
Here is your own code, showing the ['mode'] being something else.

`    // Session params
    $sessionParams = [
        'customer_email'       => $donation['email'],
        'payment_method_types' => ['card'],
        'mode'                 => 'payment',
        'success_url'          => $returnUrl,
        'cancel_url'           => $cancelUrl,
    ];`

**Comment by naokipeter** [comment]
Thanks for pointing this out. You're absolutely right. It looks like I haven't done proper regression testing. Would you mind fixing the indentation, so I can merge?

**Comment by stevenmc** [comment]
I've fixed my indentation. Thanks a lot.
I love your plugin, by the way! Thank you!

**Pull request merged**
